export default {
  LOGIN: 'LOGIN',
  SIGN_OUT: 'SIGN_OUT',
  SAVE_USER_FILES: 'SAVE_USER_FILES',
  DELETE_USER_FILE: 'DELETE_USER_FILE',
  SAVE_USER_SINGLE_FILE: 'SAVE_USER_SINGLE_FILE',
  CLEAR_USER_FILES: 'CLEAR_USER_FILES',
};
